name: Deploy Analytics Script to Cloudflare Pages

on:
  push:
    paths:
      - 'packages/script/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deployment_url: ${{ steps.deployment.outputs.url }}

    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Dependencies and Build
        run: pnpm --filter @dub/analytics-script build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=dub-cdn --commit-dirty=true
          workingDirectory: packages/script
          packageManager: pnpm

      - name: Get deployment URL
        id: deployment
        run: |
          echo "url=$(pnpm wrangler pages deployment list --project-name=dub-cdn --json | jq -r '.[0].url')" >> $GITHUB_OUTPUT
