name: Deploy Script to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/script/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies and Build
      run: |
        cd packages/script
        pnpm install
        pnpm run build

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: 'dub-analytics'
        directory: 'packages/script/dist'
