name: Playwright Tests

on:
  workflow_run:
    workflows: ['Deploy Analytics Script to Cloudflare Pages']
    types: [completed]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install
          pnpm install --filter @dub/analytics

      - name: Build workspace dependencies
        run: pnpm --filter @dub/analytics build

      - name: Install Playwright
        working-directory: apps/nextjs
        run: pnpm add -D @playwright/test

      - name: Install Playwright Browsers
        working-directory: apps/nextjs
        run: pnpm exec playwright install chromium --with-deps

      - name: Download deployment URL
        uses: actions/download-artifact@v4
        with:
          name: deployment-url
          path: .

      - name: Read Deployment URL
        id: read_url
        run: |
          echo "DUB_ANALYTICS_SCRIPT_URL=$(cat deployment_url.txt)/analytics/script.site-visit.outbound-domains.js" >> $GITHUB_ENV

      - name: Run Playwright tests
        working-directory: apps/nextjs
        run: pnpm exec playwright test
        env:
          DUB_ANALYTICS_SCRIPT_URL: ${{ env.DUB_ANALYTICS_SCRIPT_URL }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/nextjs/playwright-report/
          retention-days: 30
